-- Spell material and trade-good items for PHB/SRD casting requirements.
-- Costly consumed components use trade_goods with accurate cost_gp.

INSERT INTO public.items (slug, name, category, subcategory, source, rarity, weight_lb, cost_gp, description, properties) VALUES
('copper-wire', 'Copper wire', 'adventuring_gear', null, 'PHB', 'common', 0, 0, 'A short piece of copper wire used as a spell material component.', '{"spellMaterial":{"aliases":["short piece of copper wire","fine copper wire"]}}'),
('phosphorus', 'Phosphorus', 'adventuring_gear', null, 'PHB', 'common', 0, 0, 'A bit of phosphorus or wychwood used as a spell material component.', '{"spellMaterial":{"aliases":["bit of phosphorus","wychwood","glowworm"]}}'),
('lodestone', 'Lodestone', 'adventuring_gear', null, 'PHB', 'common', 0, 0, 'A lodestone used as a spell material component.', '{"spellMaterial":{"aliases":["lodestones"]}}'),
('bat-guano-and-sulfur', 'Bat guano and sulfur', 'adventuring_gear', null, 'PHB', 'common', 0, 0, 'A tiny ball of bat guano and sulfur used as a spell material component.', '{"spellMaterial":{"aliases":["tiny ball of bat guano and sulfur"]}}'),
('brass-brazier', 'Brass brazier', 'adventuring_gear', null, 'PHB', 'common', 3, 5, 'A brass brazier for burning incense during rituals.', '{}'),
('charcoal-incense-herbs-10gp', 'Charcoal, incense, and herbs', 'trade_goods', null, 'PHB', 'common', 1, 10, 'Charcoal, incense, and herbs worth 10 gp, consumed by fire when casting certain divination spells.', '{"spellMaterial":{"consumedByDefault":true}}'),
('lead-based-ink-10gp', 'Lead-based ink', 'trade_goods', null, 'PHB', 'common', 0, 10, 'Lead-based ink worth at least 10 gp, consumed by the magic mouth spell.', '{"spellMaterial":{"consumedByDefault":true}}'),
('pearl-worth-100-gp', 'Pearl', 'trade_goods', null, 'PHB', 'common', 0, 100, 'A pearl worth at least 100 gp used as a spell material component.', '{}'),
('owl-feather', 'Owl feather', 'adventuring_gear', null, 'PHB', 'common', 0, 0, 'An owl feather used as a spell material component.', '{}'),
('gold-dust-25-gp', 'Gold dust', 'trade_goods', null, 'PHB', 'common', 0, 25, 'Gold dust worth at least 25 gp, consumed by certain spells.', '{"spellMaterial":{"consumedByDefault":true}}'),
('divination-tokens-25-gp', 'Divination tokens', 'trade_goods', null, 'PHB', 'common', 0, 25, 'Specially marked sticks, bones, or similar tokens worth at least 25 gp.', '{}'),
('ruby-dust-50-gp', 'Ruby dust', 'trade_goods', null, 'PHB', 'common', 0, 50, 'Ruby dust worth 50 gp, consumed by the continual flame spell.', '{"spellMaterial":{"consumedByDefault":true}}'),
('powdered-silver-and-iron-100-gp', 'Powdered silver and iron', 'trade_goods', null, 'PHB', 'common', 0, 100, 'Powdered silver and iron worth at least 100 gp, consumed by certain abjuration spells.', '{"spellMaterial":{"consumedByDefault":true,"aliases":["powdered silver and iron"]}}'),
('diamond-dust-25-gp', 'Diamond dust', 'trade_goods', null, 'PHB', 'common', 0, 25, 'A pinch of diamond dust worth 25 gp, consumed by certain spells.', '{"spellMaterial":{"consumedByDefault":true}}'),
('diamond-dust-100-gp', 'Diamond dust (100 gp)', 'trade_goods', null, 'PHB', 'common', 0, 100, 'Diamond dust worth 100 gp, consumed by greater restoration and similar spells.', '{"spellMaterial":{"consumedByDefault":true}}'),
('diamond-dust-200-gp', 'Diamond dust (200 gp)', 'trade_goods', null, 'PHB', 'common', 0, 200, 'Powdered diamond worth at least 200 gp, consumed by glyph of warding.', '{"spellMaterial":{"consumedByDefault":true}}'),
('diamonds-300-gp', 'Diamonds (300 gp)', 'trade_goods', null, 'PHB', 'common', 0, 300, 'Diamonds worth 300 gp, consumed by revivify.', '{"spellMaterial":{"consumedByDefault":true}}'),
('diamond-500-gp', 'Diamond (500 gp)', 'trade_goods', null, 'PHB', 'common', 0, 500, 'A diamond worth at least 500 gp, consumed by certain high-level spells.', '{"spellMaterial":{"consumedByDefault":true}}'),
('diamond-1000-gp', 'Diamond (1,000 gp)', 'trade_goods', null, 'PHB', 'common', 0, 1000, 'A diamond worth at least 1,000 gp, consumed by raise dead and similar spells.', '{"spellMaterial":{"consumedByDefault":true}}'),
('diamond-5000-gp', 'Diamond (5,000 gp)', 'trade_goods', null, 'PHB', 'common', 0, 5000, 'Diamond dust composed of diamond, emerald, ruby, and sapphire worth at least 5,000 gp, consumed by resurrection.', '{"spellMaterial":{"consumedByDefault":true}}'),
('diamonds-25000-gp', 'Diamonds (25,000 gp)', 'trade_goods', null, 'PHB', 'common', 0, 25000, 'Diamonds worth at least 25,000 gp, consumed by true resurrection.', '{"spellMaterial":{"consumedByDefault":true}}'),
('ruby-dust-1500-gp', 'Powdered ruby (1,500 gp)', 'trade_goods', null, 'PHB', 'common', 0, 1500, 'Powdered ruby worth 1,500 gp, consumed by simulacrum.', '{"spellMaterial":{"consumedByDefault":true}}'),
('agate-1000-gp', 'Agate (1,000 gp)', 'trade_goods', null, 'PHB', 'common', 0, 1000, 'An agate worth at least 1,000 gp, consumed by the clone spell.', '{"spellMaterial":{"consumedByDefault":true}}'),
('sapphire-1000-gp', 'Sapphire (1,000 gp)', 'trade_goods', null, 'PHB', 'common', 0, 1000, 'A sapphire worth 1,000 gp used as a spell material component.', '{}'),
('black-pearl-powder-500-gp', 'Crushed black pearl', 'trade_goods', null, 'PHB', 'common', 0, 500, 'Powder of a crushed black pearl worth at least 500 gp.', '{}'),
('herbs-oils-incense-1000-gp', 'Herbs, oils, and incense', 'trade_goods', null, 'PHB', 'common', 1, 1000, 'Herbs, oils, and incense worth at least 1,000 gp, consumed by resurrection.', '{"spellMaterial":{"consumedByDefault":true}}'),
('rare-oils-unguents-1000-gp', 'Rare oils and unguents', 'trade_goods', null, 'PHB', 'common', 1, 1000, 'Rare oils and unguents worth at least 1,000 gp, consumed by heal.', '{"spellMaterial":{"consumedByDefault":true}}'),
('incense-250-gp', 'Incense (250 gp)', 'trade_goods', null, 'PHB', 'common', 0, 250, 'Incense worth at least 250 gp, consumed by hallow.', '{"spellMaterial":{"consumedByDefault":true}}'),
('ivory-strips-50-gp', 'Ivory strips', 'trade_goods', null, 'PHB', 'common', 0, 50, 'Ivory strips worth at least 50 gp each, used with hallow.', '{}'),
('jewel-1000-gp', 'Jewel (1,000 gp)', 'trade_goods', null, 'PHB', 'common', 0, 1000, 'A jewel worth at least 1,000 gp, consumed by sequester.', '{"spellMaterial":{"consumedByDefault":true}}'),
('gem-encrusted-bowl-1000-gp', 'Gem-encrusted bowl', 'trade_goods', null, 'PHB', 'common', 2, 1000, 'A gem-encrusted bowl worth at least 1,000 gp, consumed by scrying.', '{"spellMaterial":{"consumedByDefault":true}}'),
('eye-ointment-25-gp', 'Eye ointment', 'trade_goods', null, 'PHB', 'common', 0, 25, 'An ointment for the eyes costing 25 gp, made from mushroom powder, saffron, and fat, consumed by true seeing.', '{"spellMaterial":{"consumedByDefault":true}}'),
('platinum-sword-miniature-250-gp', 'Miniature platinum sword', 'trade_goods', null, 'PHB', 'common', 0, 250, 'A miniature platinum sword with a grip and pommel of copper and zinc, worth 250 gp.', '{}'),
('forked-metal-rod-250-gp', 'Forked metal rod', 'trade_goods', null, 'PHB', 'common', 1, 250, 'A forked metal rod worth at least 250 gp, attuned to a particular plane of existence.', '{}'),
('copper-coin', 'Copper coin', 'adventuring_gear', null, 'PHB', 'common', 0, 0.01, 'A copper coin used as a spell material component.', '{"spellMaterial":{"aliases":["copper piece","one copper piece"]}}'),
('pinch-of-salt', 'Pinch of salt', 'adventuring_gear', null, 'PHB', 'common', 0, 0, 'A pinch of salt used as a spell material component.', '{}'),
('burning-incense', 'Burning incense', 'adventuring_gear', null, 'PHB', 'common', 0, 0, 'Burning incense used as a spell material component.', '{"spellMaterial":{"aliases":["incense"]}}'),
('holy-water-sprinkle', 'Sprinkling of holy water', 'adventuring_gear', null, 'PHB', 'common', 0, 25, 'A sprinkling of holy water used as a spell material component.', '{"spellMaterial":{"aliases":["sprinkling of holy water"],"consumedByDefault":true}}'),
('tiny-strip-of-white-cloth', 'Tiny strip of white cloth', 'adventuring_gear', null, 'PHB', 'common', 0, 0, 'A tiny strip of white cloth used as a spell material component.', '{}'),
('beast-fur-or-feather', 'Beast fur or feather', 'adventuring_gear', null, 'PHB', 'common', 0, 0, 'Fur or a feather from a beast, used as a spell material component.', '{"spellMaterial":{"aliases":["fur or a feather from a beast"]}}')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  source = EXCLUDED.source,
  rarity = EXCLUDED.rarity,
  weight_lb = EXCLUDED.weight_lb,
  cost_gp = EXCLUDED.cost_gp,
  description = EXCLUDED.description,
  properties = EXCLUDED.properties,
  updated_at = now();
