/** PHB cleric domain spells — always prepared, unlocked at cleric levels 1/3/5/7/9. */
export interface ClericDomainSpellEntry {
  spellId: string;
  minCharacterLevel: number;
}

export const CLERIC_DOMAIN_SPELLS: Record<string, ClericDomainSpellEntry[]> = {
  knowledge: [
    { spellId: "command", minCharacterLevel: 1 },
    { spellId: "identify", minCharacterLevel: 1 },
    { spellId: "augury", minCharacterLevel: 3 },
    { spellId: "suggestion", minCharacterLevel: 3 },
    { spellId: "nondetection", minCharacterLevel: 5 },
    { spellId: "speak-with-dead", minCharacterLevel: 5 },
    { spellId: "arcane-eye", minCharacterLevel: 7 },
    { spellId: "confusion", minCharacterLevel: 7 },
    { spellId: "scrying", minCharacterLevel: 9 },
    { spellId: "legend-lore", minCharacterLevel: 9 },
  ],
  life: [
    { spellId: "bless", minCharacterLevel: 1 },
    { spellId: "cure-wounds", minCharacterLevel: 1 },
    { spellId: "lesser-restoration", minCharacterLevel: 3 },
    { spellId: "spiritual-weapon", minCharacterLevel: 3 },
    { spellId: "beacon-of-hope", minCharacterLevel: 5 },
    { spellId: "revivify", minCharacterLevel: 5 },
    { spellId: "death-ward", minCharacterLevel: 7 },
    { spellId: "guardian-of-faith", minCharacterLevel: 7 },
    { spellId: "mass-cure-wounds", minCharacterLevel: 9 },
    { spellId: "raise-dead", minCharacterLevel: 9 },
  ],
  light: [
    { spellId: "burning-hands", minCharacterLevel: 1 },
    { spellId: "faerie-fire", minCharacterLevel: 1 },
    { spellId: "flare", minCharacterLevel: 3 },
    { spellId: "scorching-ray", minCharacterLevel: 3 },
    { spellId: "daylight", minCharacterLevel: 5 },
    { spellId: "fireball", minCharacterLevel: 5 },
    { spellId: "guardian-of-faith", minCharacterLevel: 7 },
    { spellId: "wall-of-fire", minCharacterLevel: 7 },
    { spellId: "flame-strike", minCharacterLevel: 9 },
    { spellId: "scrying", minCharacterLevel: 9 },
  ],
  nature: [
    { spellId: "animal-friendship", minCharacterLevel: 1 },
    { spellId: "speak-with-animals", minCharacterLevel: 1 },
    { spellId: "barkskin", minCharacterLevel: 3 },
    { spellId: "spike-growth", minCharacterLevel: 3 },
    { spellId: "plant-growth", minCharacterLevel: 5 },
    { spellId: "wind-wall", minCharacterLevel: 5 },
    { spellId: "dominate-beast", minCharacterLevel: 7 },
    { spellId: "grasping-vine", minCharacterLevel: 7 },
    { spellId: "insect-plague", minCharacterLevel: 9 },
    { spellId: "tree-stride", minCharacterLevel: 9 },
  ],
  tempest: [
    { spellId: "fog-cloud", minCharacterLevel: 1 },
    { spellId: "thunderwave", minCharacterLevel: 1 },
    { spellId: "gust-of-wind", minCharacterLevel: 3 },
    { spellId: "shatter", minCharacterLevel: 3 },
    { spellId: "call-lightning", minCharacterLevel: 5 },
    { spellId: "sleet-storm", minCharacterLevel: 5 },
    { spellId: "control-water", minCharacterLevel: 7 },
    { spellId: "ice-storm", minCharacterLevel: 7 },
    { spellId: "destructive-wave", minCharacterLevel: 9 },
    { spellId: "insect-plague", minCharacterLevel: 9 },
  ],
  trickery: [
    { spellId: "charm-person", minCharacterLevel: 1 },
    { spellId: "disguise-self", minCharacterLevel: 1 },
    { spellId: "mirror-image", minCharacterLevel: 3 },
    { spellId: "pass-without-trace", minCharacterLevel: 3 },
    { spellId: "blink", minCharacterLevel: 5 },
    { spellId: "dispel-magic", minCharacterLevel: 5 },
    { spellId: "dimension-door", minCharacterLevel: 7 },
    { spellId: "polymorph", minCharacterLevel: 7 },
    { spellId: "dominate-person", minCharacterLevel: 9 },
    { spellId: "modify-memory", minCharacterLevel: 9 },
  ],
  war: [
    { spellId: "divine-favor", minCharacterLevel: 1 },
    { spellId: "shield-of-faith", minCharacterLevel: 1 },
    { spellId: "magic-weapon", minCharacterLevel: 3 },
    { spellId: "spiritual-weapon", minCharacterLevel: 3 },
    { spellId: "crusaders-mantle", minCharacterLevel: 5 },
    { spellId: "spirit-guardians", minCharacterLevel: 5 },
    { spellId: "freedom-of-movement", minCharacterLevel: 7 },
    { spellId: "stoneskin", minCharacterLevel: 7 },
    { spellId: "flame-strike", minCharacterLevel: 9 },
    { spellId: "hold-monster", minCharacterLevel: 9 },
  ],
};
